Improve docker checker and doc (#13)

diff --git a/localenv b/localenv
--- a/localenv
+++ b/localenv
@@ -22,6 +22,14 @@ error_usage() {
   usage
 }
 
+# Function to check if Docker is installed
+check_docker_installed() {
+  if ! command -v docker &>/dev/null; then
+    echo "Error: Docker is not installed. Please install Docker to use this script."
+    exit 1
+  fi
+}
+
 # Function to check if a file exists
 check_file_exists() {
   local file_to_check=$1
@@ -50,8 +58,12 @@ if [[ "$language" == "--help" || "$script_path" == "--help" ]]; then
   usage
 fi
 
+echo "Pre-flight checking"
 # Validate input arguments
 check_input "$language" "$script_path"
+
+# Ensure Docker is installed
+check_docker_installed
 
 # Ensure the config file exists
 check_file_exists "$CONFIG_FILE_PATH"
@@ -61,6 +73,7 @@ image=$(yq e ".$language.image" "$CONFIG_FILE_PATH")
 container_name=$(yq e ".$language.default_container_name" "$CONFIG_FILE_PATH")
 base_cmd=$(yq e ".$language.base_command" "$CONFIG_FILE_PATH")
 
+echo "Pre-flight checking - OK"
 # Command to execute
 echo "Execute $language script in Docker..."
 
